POST http://localhost:5000/usuarios
Content-Type: application/json

{
    "nombre" : "leo"
}

###
POST http://localhost:5000/usuarios/reset
Content-Type: application/json

{
    "secreto" : "3OPqYnS1wPpsmUM"
}

###
GET http://localhost:5000/usuarios

###
POST http://localhost:5000/montos
Content-Type: application/json

{
    "id" : "4d472208-91f8-446f-bf7e-ec674df4c709",
    "nombre" : "leo",
    "monto" : [20, 134]
}

###
PUT  http://localhost:5000/montos/4d472208-91f8-446f-bf7e-ec674df4c709/leo
Content-Type: application/json

{
    "monto" : [20, 1340]
}

###
POST http://localhost:5000/pagar
Content-Type: application/json

{
    "id" : "a7503934-aa56-4737-8ca6-a1cf4a6962aa",
    "nombre" : "nico",
    "deuda_total" : 200,
    "pago_del_usuario" : 900,
    "fecha" : "20-6-24"
}

###
GET http://localhost:5000/pagar

###
POST http://localhost:5000/pagar/reset
Content-Type: application/json

{
    "secreto" : "7ri1GIrbw8hkAwK"
}